controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

adminControllers:
    resource: ../src/AdminController/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
