controllers:
    resource: ../src/Controller/
    type: annotation

adminControllers:
    resource: ../src/AdminController/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
