controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

adminControllers:
    resource:
        path: ../src/AdminController/
        namespace: App\AdminController
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: attribute
